<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>Topoi.Quantum</RootNamespace>
    <AssemblyName>Topoi.Quantum</AssemblyName>

    <IsPackable>true</IsPackable>

    <PackageId>Topoi.Quantum</PackageId>
    <Title>Topoi Quantum</Title>

    <Description>
      A professional .NET quantum toolkit for circuit building,
      dense state-vector simulation, sampling, estimation,
      and quantum-computing education.
    </Description>

    <PackageTags>
      quantum;qasm;simulator;dotnet;csharp;sampler;estimator
    </PackageTags>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md"
          Pack="true"
          PackagePath="\" />
  </ItemGroup>
</Project>