<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuantumComputer.Core\QuantumComputer.Core.csproj" />
    <ProjectReference Include="..\QuantumComputer.Drawing\QuantumComputer.Drawing.csproj" />
    <ProjectReference Include="..\QuantumComputer.Parsing\QuantumComputer.Parsing.csproj" />
  </ItemGroup>

</Project>
