<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Topoi.Quantum.OpenQasm</RootNamespace>
    <AssemblyName>Topoi.Quantum.OpenQasm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Topoi.Quantum\Topoi.Quantum.csproj" />
  </ItemGroup>

</Project>
